/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth_.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth_.forgot-password'
import { Route as AuthConfirmedRouteImport } from './routes/auth_.confirmed'
import { Route as AuthCheckEmailRouteImport } from './routes/auth_.check-email'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AppPlaneringRouteImport } from './routes/_app/planering'
import { Route as AppPengarRouteImport } from './routes/_app/pengar'
import { Route as AppKalenderRouteImport } from './routes/_app/kalender'
import { Route as AppJobbRouteImport } from './routes/_app/jobb'
import { Route as AppInstallningarRouteImport } from './routes/_app/installningar'
import { Route as AppInsikterRouteImport } from './routes/_app/insikter'
import { Route as AppIdagRouteImport } from './routes/_app/idag'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppInstallningarIndexRouteImport } from './routes/_app/installningar.index'
import { Route as AppInstallningarProfilOchReglerRouteImport } from './routes/_app/installningar.profil-och-regler'
import { Route as AppInstallningarLonArbeteRouteImport } from './routes/_app/installningar.lon-arbete'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth_/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth_/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmedRoute = AuthConfirmedRouteImport.update({
  id: '/auth_/confirmed',
  path: '/auth/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/auth_/check-email',
  path: '/auth/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlaneringRoute = AppPlaneringRouteImport.update({
  id: '/planering',
  path: '/planering',
  getParentRoute: () => AppRoute,
} as any)
const AppPengarRoute = AppPengarRouteImport.update({
  id: '/pengar',
  path: '/pengar',
  getParentRoute: () => AppRoute,
} as any)
const AppKalenderRoute = AppKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AppRoute,
} as any)
const AppJobbRoute = AppJobbRouteImport.update({
  id: '/jobb',
  path: '/jobb',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallningarRoute = AppInstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => AppRoute,
} as any)
const AppInsikterRoute = AppInsikterRouteImport.update({
  id: '/insikter',
  path: '/insikter',
  getParentRoute: () => AppRoute,
} as any)
const AppIdagRoute = AppIdagRouteImport.update({
  id: '/idag',
  path: '/idag',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallningarIndexRoute = AppInstallningarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInstallningarRoute,
} as any)
const AppInstallningarProfilOchReglerRoute =
  AppInstallningarProfilOchReglerRouteImport.update({
    id: '/profil-och-regler',
    path: '/profil-och-regler',
    getParentRoute: () => AppInstallningarRoute,
  } as any)
const AppInstallningarLonArbeteRoute =
  AppInstallningarLonArbeteRouteImport.update({
    id: '/lon-arbete',
    path: '/lon-arbete',
    getParentRoute: () => AppInstallningarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/idag': typeof AppIdagRoute
  '/insikter': typeof AppInsikterRoute
  '/installningar': typeof AppInstallningarRouteWithChildren
  '/jobb': typeof AppJobbRoute
  '/kalender': typeof AppKalenderRoute
  '/pengar': typeof AppPengarRoute
  '/planering': typeof AppPlaneringRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/installningar/lon-arbete': typeof AppInstallningarLonArbeteRoute
  '/installningar/profil-och-regler': typeof AppInstallningarProfilOchReglerRoute
  '/installningar/': typeof AppInstallningarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/idag': typeof AppIdagRoute
  '/insikter': typeof AppInsikterRoute
  '/jobb': typeof AppJobbRoute
  '/kalender': typeof AppKalenderRoute
  '/pengar': typeof AppPengarRoute
  '/planering': typeof AppPlaneringRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/installningar/lon-arbete': typeof AppInstallningarLonArbeteRoute
  '/installningar/profil-och-regler': typeof AppInstallningarProfilOchReglerRoute
  '/installningar': typeof AppInstallningarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/idag': typeof AppIdagRoute
  '/_app/insikter': typeof AppInsikterRoute
  '/_app/installningar': typeof AppInstallningarRouteWithChildren
  '/_app/jobb': typeof AppJobbRoute
  '/_app/kalender': typeof AppKalenderRoute
  '/_app/pengar': typeof AppPengarRoute
  '/_app/planering': typeof AppPlaneringRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/auth_/check-email': typeof AuthCheckEmailRoute
  '/auth_/confirmed': typeof AuthConfirmedRoute
  '/auth_/forgot-password': typeof AuthForgotPasswordRoute
  '/auth_/reset-password': typeof AuthResetPasswordRoute
  '/_app/installningar/lon-arbete': typeof AppInstallningarLonArbeteRoute
  '/_app/installningar/profil-och-regler': typeof AppInstallningarProfilOchReglerRoute
  '/_app/installningar/': typeof AppInstallningarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/idag'
    | '/insikter'
    | '/installningar'
    | '/jobb'
    | '/kalender'
    | '/pengar'
    | '/planering'
    | '/auth/callback'
    | '/auth/check-email'
    | '/auth/confirmed'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/installningar/lon-arbete'
    | '/installningar/profil-och-regler'
    | '/installningar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/idag'
    | '/insikter'
    | '/jobb'
    | '/kalender'
    | '/pengar'
    | '/planering'
    | '/auth/callback'
    | '/auth/check-email'
    | '/auth/confirmed'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/installningar/lon-arbete'
    | '/installningar/profil-och-regler'
    | '/installningar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/idag'
    | '/_app/insikter'
    | '/_app/installningar'
    | '/_app/jobb'
    | '/_app/kalender'
    | '/_app/pengar'
    | '/_app/planering'
    | '/auth_/callback'
    | '/auth_/check-email'
    | '/auth_/confirmed'
    | '/auth_/forgot-password'
    | '/auth_/reset-password'
    | '/_app/installningar/lon-arbete'
    | '/_app/installningar/profil-och-regler'
    | '/_app/installningar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthConfirmedRoute: typeof AuthConfirmedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/reset-password': {
      id: '/auth_/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/forgot-password': {
      id: '/auth_/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/confirmed': {
      id: '/auth_/confirmed'
      path: '/auth/confirmed'
      fullPath: '/auth/confirmed'
      preLoaderRoute: typeof AuthConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/check-email': {
      id: '/auth_/check-email'
      path: '/auth/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/planering': {
      id: '/_app/planering'
      path: '/planering'
      fullPath: '/planering'
      preLoaderRoute: typeof AppPlaneringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengar': {
      id: '/_app/pengar'
      path: '/pengar'
      fullPath: '/pengar'
      preLoaderRoute: typeof AppPengarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kalender': {
      id: '/_app/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AppKalenderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobb': {
      id: '/_app/jobb'
      path: '/jobb'
      fullPath: '/jobb'
      preLoaderRoute: typeof AppJobbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installningar': {
      id: '/_app/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof AppInstallningarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insikter': {
      id: '/_app/insikter'
      path: '/insikter'
      fullPath: '/insikter'
      preLoaderRoute: typeof AppInsikterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/idag': {
      id: '/_app/idag'
      path: '/idag'
      fullPath: '/idag'
      preLoaderRoute: typeof AppIdagRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installningar/': {
      id: '/_app/installningar/'
      path: '/'
      fullPath: '/installningar/'
      preLoaderRoute: typeof AppInstallningarIndexRouteImport
      parentRoute: typeof AppInstallningarRoute
    }
    '/_app/installningar/profil-och-regler': {
      id: '/_app/installningar/profil-och-regler'
      path: '/profil-och-regler'
      fullPath: '/installningar/profil-och-regler'
      preLoaderRoute: typeof AppInstallningarProfilOchReglerRouteImport
      parentRoute: typeof AppInstallningarRoute
    }
    '/_app/installningar/lon-arbete': {
      id: '/_app/installningar/lon-arbete'
      path: '/lon-arbete'
      fullPath: '/installningar/lon-arbete'
      preLoaderRoute: typeof AppInstallningarLonArbeteRouteImport
      parentRoute: typeof AppInstallningarRoute
    }
  }
}

interface AppInstallningarRouteChildren {
  AppInstallningarLonArbeteRoute: typeof AppInstallningarLonArbeteRoute
  AppInstallningarProfilOchReglerRoute: typeof AppInstallningarProfilOchReglerRoute
  AppInstallningarIndexRoute: typeof AppInstallningarIndexRoute
}

const AppInstallningarRouteChildren: AppInstallningarRouteChildren = {
  AppInstallningarLonArbeteRoute: AppInstallningarLonArbeteRoute,
  AppInstallningarProfilOchReglerRoute: AppInstallningarProfilOchReglerRoute,
  AppInstallningarIndexRoute: AppInstallningarIndexRoute,
}

const AppInstallningarRouteWithChildren =
  AppInstallningarRoute._addFileChildren(AppInstallningarRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppIdagRoute: typeof AppIdagRoute
  AppInsikterRoute: typeof AppInsikterRoute
  AppInstallningarRoute: typeof AppInstallningarRouteWithChildren
  AppJobbRoute: typeof AppJobbRoute
  AppKalenderRoute: typeof AppKalenderRoute
  AppPengarRoute: typeof AppPengarRoute
  AppPlaneringRoute: typeof AppPlaneringRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppIdagRoute: AppIdagRoute,
  AppInsikterRoute: AppInsikterRoute,
  AppInstallningarRoute: AppInstallningarRouteWithChildren,
  AppJobbRoute: AppJobbRoute,
  AppKalenderRoute: AppKalenderRoute,
  AppPengarRoute: AppPengarRoute,
  AppPlaneringRoute: AppPlaneringRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthConfirmedRoute: AuthConfirmedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
