/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth_.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth_.forgot-password'
import { Route as AuthConfirmedRouteImport } from './routes/auth_.confirmed'
import { Route as AuthCheckEmailRouteImport } from './routes/auth_.check-email'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AppPengarRouteImport } from './routes/_app/pengar'
import { Route as AppKalenderRouteImport } from './routes/_app/kalender'
import { Route as AppJobbRouteImport } from './routes/_app/jobb'
import { Route as AppInstallningarRouteImport } from './routes/_app/installningar'
import { Route as AppInsikterRouteImport } from './routes/_app/insikter'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth_/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth_/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmedRoute = AuthConfirmedRouteImport.update({
  id: '/auth_/confirmed',
  path: '/auth/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/auth_/check-email',
  path: '/auth/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPengarRoute = AppPengarRouteImport.update({
  id: '/pengar',
  path: '/pengar',
  getParentRoute: () => AppRoute,
} as any)
const AppKalenderRoute = AppKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AppRoute,
} as any)
const AppJobbRoute = AppJobbRouteImport.update({
  id: '/jobb',
  path: '/jobb',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallningarRoute = AppInstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => AppRoute,
} as any)
const AppInsikterRoute = AppInsikterRouteImport.update({
  id: '/insikter',
  path: '/insikter',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/insikter': typeof AppInsikterRoute
  '/installningar': typeof AppInstallningarRoute
  '/jobb': typeof AppJobbRoute
  '/kalender': typeof AppKalenderRoute
  '/pengar': typeof AppPengarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/insikter': typeof AppInsikterRoute
  '/installningar': typeof AppInstallningarRoute
  '/jobb': typeof AppJobbRoute
  '/kalender': typeof AppKalenderRoute
  '/pengar': typeof AppPengarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/insikter': typeof AppInsikterRoute
  '/_app/installningar': typeof AppInstallningarRoute
  '/_app/jobb': typeof AppJobbRoute
  '/_app/kalender': typeof AppKalenderRoute
  '/_app/pengar': typeof AppPengarRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/auth_/check-email': typeof AuthCheckEmailRoute
  '/auth_/confirmed': typeof AuthConfirmedRoute
  '/auth_/forgot-password': typeof AuthForgotPasswordRoute
  '/auth_/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/insikter'
    | '/installningar'
    | '/jobb'
    | '/kalender'
    | '/pengar'
    | '/auth/callback'
    | '/auth/check-email'
    | '/auth/confirmed'
    | '/auth/forgot-password'
    | '/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/insikter'
    | '/installningar'
    | '/jobb'
    | '/kalender'
    | '/pengar'
    | '/auth/callback'
    | '/auth/check-email'
    | '/auth/confirmed'
    | '/auth/forgot-password'
    | '/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/insikter'
    | '/_app/installningar'
    | '/_app/jobb'
    | '/_app/kalender'
    | '/_app/pengar'
    | '/auth_/callback'
    | '/auth_/check-email'
    | '/auth_/confirmed'
    | '/auth_/forgot-password'
    | '/auth_/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthConfirmedRoute: typeof AuthConfirmedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/reset-password': {
      id: '/auth_/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/forgot-password': {
      id: '/auth_/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/confirmed': {
      id: '/auth_/confirmed'
      path: '/auth/confirmed'
      fullPath: '/auth/confirmed'
      preLoaderRoute: typeof AuthConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/check-email': {
      id: '/auth_/check-email'
      path: '/auth/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pengar': {
      id: '/_app/pengar'
      path: '/pengar'
      fullPath: '/pengar'
      preLoaderRoute: typeof AppPengarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kalender': {
      id: '/_app/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AppKalenderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobb': {
      id: '/_app/jobb'
      path: '/jobb'
      fullPath: '/jobb'
      preLoaderRoute: typeof AppJobbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installningar': {
      id: '/_app/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof AppInstallningarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insikter': {
      id: '/_app/insikter'
      path: '/insikter'
      fullPath: '/insikter'
      preLoaderRoute: typeof AppInsikterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInsikterRoute: typeof AppInsikterRoute
  AppInstallningarRoute: typeof AppInstallningarRoute
  AppJobbRoute: typeof AppJobbRoute
  AppKalenderRoute: typeof AppKalenderRoute
  AppPengarRoute: typeof AppPengarRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInsikterRoute: AppInsikterRoute,
  AppInstallningarRoute: AppInstallningarRoute,
  AppJobbRoute: AppJobbRoute,
  AppKalenderRoute: AppKalenderRoute,
  AppPengarRoute: AppPengarRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthConfirmedRoute: AuthConfirmedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
